### ISSUE TITLE
How best to handle edge case of truncated response?

### ISSUE THREAD

**Issue by titanism** [hildjj/dohdec#40]
If `flags_tc` is `true`, how would you recommend to handle the truncated response?  Emit a `dns.BADRESP` or `dns.FORMERR` error?  Or retry with TCP (although that would break DoH trust).  Reference code at <https://github.com/EduardoRuizM/native-dnssec-dns/blob/fc27face6c64ab53675840bafc81f70bab48a743/lib/client.js#L352-L366>.

**Comment by hildjj** [comment]
Hm.  RFC 8484 says:

```
   A DoH server is allowed to answer queries with any valid DNS
   response.  For example, a valid DNS response might have the TC
   (truncation) bit set in the DNS header to indicate that the server
   was not able to retrieve a full answer for the query but is providing
   the best answer it could get.
```

So just switching to TCP might not solve the problem.
