### ISSUE TITLE
docs: mention 🍊 `tangerine` if the user needs a complete 1:1 replacement for `dns.promises.Resolver`?

### ISSUE THREAD

**Issue by titanism** [hildjj/dohdec#42]
Hey 👋   Just writing to express thanks for making `dohdec` &ndash; it made creating 🍊 [Tangerine](https://github.com/forwardemail/tangerine) `npm install tangerine` possible.  [We shared thanks](https://github.com/forwardemail/tangerine#what-projects-were-used-for-inspiration) in our README too!  Just passing this note along in case you also wanted to mention in `dohdec`'s README this project.  It uses `dohdec` under the hood!

**Comment by hildjj** [comment]
Nice.  I was planning on some of those features, but I'll point people to you instead.

**Comment by hildjj** [comment]
I'm open to that.  I'd need to review who else has contributed and get sign-off from them.
