### ISSUE TITLE
How to use POST method in dohdec-cli ?

### ISSUE THREAD

**Issue by PaTTeeL** [hildjj/dohdec#43]
How to trigger the dohdec-cli uses POST request for getting response from DoH servers ?
I saw the option
`Options:
   -g, --get                     Force http GET for DNS-format lookups (default: true)`

and tried all the ways as below:
```
dohdec -dv www.cloudflare.com aaaa
dohdec -dv www.cloudflare.com aaaa -g 0
dohdec -dv www.cloudflare.com aaaa -g false
```
the program always shows
```
DNSoverHTTPS options: {
  contentType: 'application/dns-message',
  http2: true,
  preferPost: false,
  url: 'https://cloudflare-dns.com/dns-query',
  userAgent: 'dohdec v5.0.3'
}
...
HTTP GET URL: https://cloudflare-dns.com/dns-query?dns=AAABAAABAAAAAAABA3d3dwpjbG91ZGZsYXJlA2NvbQAAHAABAAApEAAAAAAAAFEADABNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
So how can I make dohdec-cli use the POST method to get the response from DoH servers?

**Comment by hildjj** [comment]
This turned out to be a bug in the CLI.  WillFix.

**Comment by hildjj** [comment]
Once this is fixed, you'll want to use the `-d` flag as well.  I think you have to ask for DNS-formatted responses if you use POST.
