### ISSUE TITLE
Switch to MIT license

### ISSUE THREAD

**Issue by hildjj** [hildjj/dohdec#47]
As requested in #42, I would like to switch to the MIT license.  Hopefully this isn't terribly controversial.

In order to do so, I need approval from the following folks:

@gnarea
@imcotton

The following folks have contributed doc changes, and get to have an opinion if they respond quickly enough:

@titanism 
@zdeneksvarc

**Comment by gnarea** [comment]
Sounds good to me @hildjj! 👍🏾

**Comment by imcotton** [comment]
I agree, also delegate my consent on any further inquire just in case.
