### ISSUE TITLE
Add (OPTIONAL!) support for ECS

### ISSUE THREAD

**Issue by hildjj** [hildjj/dohdec#9]
See[ RFC 7871](https://tools.ietf.org/html/rfc7871).

This potentially leaks enough personal info that not everyone will want it.

**Comment by imcotton** [comment]
Looked into the code:

https://github.com/hildjj/dohdec/blob/96942650d152a2817ffad48fa1000968a2990751/lib/dnsUtils.js#L71-L76

Am I right it would only requires additional `opts.ip` to be included to support ECS?
